name = "ngo-quyen"
main = ".open-next/worker.js"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "ngoquyen"
database_id = "1c9e6f28-d762-4f5d-a2c8-4219ff7f58bf"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "ngo-quyen"
